config/routes.rb
Rails.application.routes.draw do

  get 'conversations/index'

  root 'pages#home'


  devise_for :users

  get 'pages/contact'
  get 'pages/about'


  resources :users
  resources :moms

  resources :conversations do
    resources :messages

  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mom.rb
class Mom < ApplicationRecord
  mount_uploader :image, ImageUploader

  # belongs_to :user, dependent: :destroy

  belongs_to :user, optional: true, dependent: :destroy


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :mom

  acts_as_messageable

  def name
    "User #{id}"
  end

  def mailboxer_email(object)
    nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def index
    @conversations = current_user.mailbox.conversations
  end

  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
  end

  def new
    @recipients = User.all - [current_user]
  end


  def create
    recipient = User.find(params[:user_id])
    recipt = current_user.send_message(recipient, params[:body], params[:subject])
    redirect_to conversation_path(recipt.conversation)
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

before_action :set_conversation


def create
  receipt = current_user.reply_to_conversation(@conversation, params[:body])
  redirect_to conversation_path(receipt.conversation)

end










  private

  def set_conversation
    @conversation = current_user.mailbox.conversations.find(params[:conversation_id])
  end

end

app/controllers/moms_controller.rb
class MomsController < ApplicationController
  before_action :set_mom, only: [:show, :edit, :update, :destroy]

  # GET /moms
  # GET /moms.json
  def index
    @moms = Mom.all
  end

  # GET /moms/1
  # GET /moms/1.json
  def show
  end

  # GET /moms/new
  def new
    @mom = Mom.new
  end

  # GET /moms/1/edit
  def edit
  end

  # POST /moms
  # POST /moms.json
  def create
    @mom = current_user.build_mom(mom_params)

    respond_to do |format|
      if @mom.save
        format.html { redirect_to @mom, notice: 'Mom was successfully created.' }
        format.json { render :show, status: :created, location: @mom }
      else
        format.html { render :new }
        format.json { render json: @mom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moms/1
  # PATCH/PUT /moms/1.json
  def update
    respond_to do |format|
      if @mom.update(mom_params)
        format.html { redirect_to @mom, notice: '更新成功！' }
        format.json { render :show, status: :ok, location: @mom }
      else
        format.html { render :edit }
        format.json { render json: @mom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moms/1
  # DELETE /moms/1.json
  def destroy
    @mom.destroy
    respond_to do |format|
      format.html { redirect_to moms_url, notice: 'Mom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mom
      @mom = Mom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mom_params
      params.require(:mom).permit(:name, :age, :live, :children, :profile, :wish, :image, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show

    @user = User.find(params[:id])
    @mom = @user.mom


  end

  def edit
  end





  private

      def user_params
        params.require(:user).permit(:email)
      end

      def mom_params
        params.require(:mom).permit(:name, :age, :live, :children, :profile, :wish, :image,:user_id)
      end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/moms_helper.rb
module MomsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/index.html.erb
<h1>Conversations#index</h1>

<%= @conversations.each do |conversation| %>

  <div>
    <%= link_to conversation.subject, conversation_path(conversation) %>
  </div>

<% end %>

<% link_to "new conversation", new_conversation_path %>

app/views/conversations/new.html.erb
<h1>new conversation</h1>

<%= form_tag conversations_path, method: :post do %>

<div>
  <%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :name) %>
</div>

<div>
  <%= text_field_tag :subject,nil, placeholder: "subject" %>
</div>


<div>
  <%= text_area_tag :body, nil, placeholder: "leave a comment" %>
</div>

<%= submit_tag %>

<% end %>

app/views/conversations/show.html.erb
<h1><%= @conversation.subject %></h1>

<% @conversation.receipts_for(current_user).each do |receipt| %>
<div>
  <div><%= receipt.message.sender.name %> commented:</div>
  <p><%= receipt.message.body %></p>
</div>

<% end %>


<%= form_tag conversation_messages_path(@conversation), method: :post do %>

    <div>
      <%= text_area_tag :body %>
    </div>

    <%= submit_tag %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Singlemom</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/moms/_form.html.erb
<%= form_for(mom) do |f| %>
  <% if mom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mom.errors.count, "error") %> prohibited this mom from being saved:</h2>

      <ul>
      <% mom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mom-form-wrapper">


  <div class="field">
    <%= f.label :名前 %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :写真 %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :年齢 %><br>
    <%= f.number_field :age %>
  </div><br>

  <div class="field">
    <%= f.label :住んでいるところ %><br>
    <%= f.text_field :live %>
  </div>

  <div class="field">
    <%= f.label :子供のこと %><br>
    <%= f.text_area :children %>
  </div>

  <div class="field">
    <%= f.label :自己紹介 %><br>
    <%= f.text_area :profile %>
  </div>

  <div class="field">
    <%= f.label :理想の人物 %><br>
    <%= f.text_area :wish %>
  </div>

  <div class="actions">
    <%= f.submit '登録する' %>
  </div>

</div>


<% end %>

app/views/moms/_mom.html.erb
  <div class="col-xs-6 col-md-3">
      <%= link_to image_tag(mom.image), mom, :class => "thumbnail", :target => "_blank" %>
  </div>

app/views/moms/edit.html.erb
<%= render 'shared/header' %>

<div class="container">

  <div class="edit-mom-wrapper">




<h1 id="mom-edit-title">編集画面</h1>

<%= render 'form', mom: @mom %>

<%= link_to 'Show', @mom %> |
<%= link_to 'Back', moms_path %>

</div>

</div>





<%= render 'shared/footer' %>

app/views/moms/index.html.erb
<%= render 'shared/header' %>


<p id="notice"><%= notice %></p>

<div class="container">

  <div class="mom-index-wrapper">

  <h1>理想の人を探す</h1>

  <div class="row">

    <%= render @moms %>


  </div>
</div>
<!-- mom-index-wrapper -->


</div>
<!-- container -->


<%= render 'shared/footer' %>

app/views/moms/new.html.erb
<%= render 'shared/header' %>

<div class="container">

  <div class="mom-new-wrapper">


    <h1>自己紹介画面</h1>

    <%= render 'form', mom: @mom %>

    <%= link_to '戻る', moms_path %>

  </div>
<!-- mom-new-wrapper -->


</div>
<!-- container -->



<%= render 'shared/footer' %>

app/views/moms/show.html.erb
<%= render 'shared/header' %>
<p id="notice"><%= notice %></p>

<div class="container">

  <div class="mom-show-wrapper">

    <h2>登録内容</h2>

    <p>
      <%= image_tag(@mom.image) %>
    </p>

<p>
  <strong>名前</strong>
  <%= @mom.name %>
</p>



<p>
  <strong>年齢</strong>
  <%= @mom.age %>歳
</p>

<p>
  <strong>おところ</strong>
  <%= @mom.live %>
</p>

<p>
  <strong>子供について</strong>
  <%= @mom.children %>
</p>

<p>
  <strong>自己紹介</strong>
  <%= @mom.profile %>
</p>

<p id="last-show">
  <strong>理想の人</strong>
  <%= @mom.wish %>
</p>




<%= link_to 'Edit', edit_mom_path(@mom) %> |
<%= link_to 'Back', moms_path %>

</div>

</div>

<%= render 'shared/footer' %>

app/views/pages/about.html.erb
<%= render 'shared/header' %>



  <div class="about-consept">

    <div class="col-md-5">
    </div>

    <div class="col-md-7">
      <h1>- CONSEPT -</h1>

      <h2>シングルマザー、<br>
        シングルファザーが<br>
        安心して出会えるサイト。<br>
        <br>
        お互いに理解し合える相手を<br>
        見つける手助けをする。<br>
      </h2>


    </div>

  <!-- </div> -->


</div>




<%= render 'shared/footer' %>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<%= render 'shared/header' %>


<div class="top-image">

  <div class="bg-inner">

    <h2>Dear Mom....</h2>
    <p>シングルマザー・ファザー専用コミュニティサイト</p>

    <%= link_to 'はじめる', new_mom_path %>

  </div>

</div>

<div class="container">

</div>

<%= render 'shared/footer' %>

app/views/shared/_footer.html.erb
<footer>
  &copy copyright sasakura-company
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Dear Mom...", root_path, { :class => "navbar-brand" } %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to '自己紹介する', new_mom_path %></li>
          <li><%= link_to '理想の人をさがす', moms_path %></li>
          <li><%= link_to 'サイトについて', pages_about_path %></li>

          <% if user_signed_in? %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">アカウント <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'プロフィール', current_user %></li>
              <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            </ul>

        <% else %>
          <li><%= link_to 'サインアップ', new_user_registration_path %></li>
          <li><%= link_to 'ログイン', new_user_session_path %></li>
        <% end %>

      </li>


      </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<%= render 'shared/header' %>

<div class="container">

  <div class="user-show-wrapper">


    <h2><%= @user.email %><%= link_to '[ 変更 ]', edit_user_registration_path %></h2>


<div class="row">
  <div class="col-md-6">
    <p><%= image_tag(@mom.image) %></p>
    <p id="edit-mom"><%= link_to '自己紹介変更', edit_mom_path %></p>

  </div>

  <div class="col-md-6">


  <p>
  <strong>名前</strong>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
  <%= @mom.name %>
  </p>



  <p>
  <strong>年齢</strong>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
  <%= @mom.age %>歳
  </p>

  <p>
  <strong>おところ</strong>&nbsp&nbsp&nbsp&nbsp
  <%= @mom.live %>
  </p>


  <p>
  <strong>自己紹介</strong>&nbsp&nbsp&nbsp&nbsp
  <%= @mom.profile %>
  </p>

  <p id="last-show">
  <strong>理想の人</strong>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
  <%= @mom.wish %>
  </p>

  <p>
    <strong>子供について</strong>&nbsp&nbsp&nbsp&nbsp
    <%= @mom.children %>
  </p>


</div>

<!-- md-6 -->

</div>
<!-- row -->

  </div>

</div>




<%= render 'shared/footer' %>